# Generated by Django 4.1.3 on 2022-11-09 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_social'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social',
            new_name='Care',
        ),
    ]
