# Generated by Django 4.1.3 on 2022-11-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_type_care_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='cares',
            field=models.ManyToManyField(to='main_app.care'),
        ),
    ]
